# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-05 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0006_auto_20200805_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
