# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-10 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0008_nameitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField(default='')),
                ('startdate', models.TextField(default='')),
                ('enddate', models.TextField(default='')),
                ('qualifications', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(default='')),
                ('role', models.TextField(default='')),
                ('startdate', models.TextField(default='')),
                ('enddate', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
